### PR TITLE
SQLite3  Support

### PR DESCRIPTION
**Pull request by GochoMugo**
Adds **SQLite3** support, as per **issue #7**

**Changes:**
- **monsql** exports two classes, `monsql.SQLite3` and `monsql.MySQL` for the different database objects
- Both of the classes, `SQLite3` and `MySQL` inherit from a common class, `Database`
- `Database` class is placed in `monsql/db.py`
- `SQLite3` class is placed in `monsql/wrapper_sqlite3.py`
- `MySQL` class is placed in `monsql/wrapper_mysql.py`
- All configuration values or consonants are placed in `monsql/config.py`
- The `Table` class is placed in `monsql/table.py`

**NOTE:**
- **tests** will break. This is due to change in interface of the module. I have decided **not** to work on this issue from this branch as much work is required for the tests to work correctly.
- more documentation may be added as this merge request is discussed.

### CODE REVIEW

**Comment by firstprayer** [comment]
I've pulled your code locally and tested it. I use the following code to unify the interface:

    class DB_TYPES:
	MYSQL = 'MySQL'
	SQLITE3 = 'SQLite3'

    def MonSQL(host=None, port=None, username=None, password=None, dbname=None, dbpath=None, dbtype=None):
	    if dbtype is None:
            raise MonSQLException('Database type must be specified')

	    if dbtype == DB_TYPES.MYSQL:
		    return MySQL(host, port, username, password, dbname)
	    elif dbtype == DB_TYPES.SQLITE3:
		    return SQLite3(dbpath)
	    else:
		    raise MonSQLException('Database type %s not supported' %dbtype)


With this now I can run the tests on either database. 

And now it yields the following errors when testing on sqlite3:

    File "/Users/taiyuanz/git/monsql/monsql/db.py", line 99, in is_table_existed
        self.__cursor.execute('show tables')
    OperationalError: near "show": syntax error

It seems the command for listing tables in sqlite3 is different. Please fix this.

You can find the codes in my branch https://github.com/firstprayer/monsql/tree/GochoMugo-sqlite3

**Comment by GochoMugo** [comment]
I have looked at the code. There seems to SQL syntax differences in SQLite3 and MySQL. This must have been expected.

See this question here: http://stackoverflow.com/questions/82875/how-do-i-list-the-tables-in-a-sqlite-database-file

I suggest we:

* delay merging my __sqlite3__ branch into develop until we define a fashionable way of handling such syntax differences.
* create a sqlite3 branch on your remote repository to which we will push more commits and PR's as we work in fixing issue above.
* work on tests as in issue #11

**Comment by firstprayer** [comment]
I think one way to do this is through overriding. Now the problems comes from showing the table list. We could add a new method "list_tables" to Database class (abstract method maybe), and override this method with specific implementation in SQLite3 and MySQL class. Now, in is_table_existed method, it should called the self.list_tables method. 

It seems github can only send pull request to default branch, which is the *develop* branch now. Let's use the  GochoMugo-sqlite3 branch for this functionality now.

**Comment by GochoMugo** [comment]
Overriding is usually fun :100: but what if we employed a dictionary that holds syntax strings that can be  accessed and modified by the `Table`/`Database` classes on demand. For example:

```python
my_sql = {"show_tables": "SHOW tables"}
sqlite3 = {"show_tables": "SELECT name FROM sqlite_master WHERE type = 'table'"}
# now if we want to show tables
cursor.execute(mysql.get("show_tables")) # for mysql
cursor.execeute(sqlite3.get("show_tables")) # for sqlite3
```

So for the different SQL versions, we have them define different dictionaries for their syntax.

**Comment by firstprayer** [comment]
Hmm I don't understand what you mean...you mean put this code in Database class? How to do that? Besides it sounds not very OOP...

**Comment by GochoMugo** [comment]
The `MySQL` and `SQLite3` classes both inherit a syntax table/dictionary from `Database`. Wherever there is syntax differences, the sub-class is responsible to redefining the syntax in the dictionary.

That example was just a shallow illustration. :smile:

**Comment by firstprayer** [comment]
Actually I'm working on this right now. It's kind of tricky... When I finish I'll push the result to develop branch....

**Comment by firstprayer** [comment]
I think your idea is also through inherit...still I believe overriding a method is better than overriding a variable. I can define this as an abstract method, so the super class doesn't need to concern about actually implementation at all.

**Comment by firstprayer** [comment]
I've pushed my modifications up to the GochoMugo-sqlite3 branch. You can merge them to your local branch. If everything is fine, publish your merged and updated branch to this pull request and I'll merge it to the develop branch. 

Let's take care of the test case issue once this part is done.

**Comment by firstprayer** [comment]
Merged into develop already. Great job :)

**Comment by GochoMugo** [comment]
Hey! I got time to experiment a little bit with the SQL string templating that I was vouching for earlier. It is on my [sql-string-templating branch](https://github.com/GochoMugo/monsql/tree/sql-string-templating). Give me your thoughts about it. _(FYI: it is **not** complete)_

**Pull request merged**
